ALTER TABLE "Integration" ADD COLUMN "syncEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Integration" ADD COLUMN "syncLockedUntil" REAL NOT NULL DEFAULT 0;
ALTER TABLE "Integration" ADD COLUMN "syncCursor" TEXT;
ALTER TABLE "Integration" ADD COLUMN "lastSyncedAt" DATETIME;
ALTER TABLE "Integration" ADD COLUMN "syncError" TEXT;
ALTER TABLE "Incident" ADD COLUMN "sourceSyncStatus" TEXT NOT NULL DEFAULT 'NOT_REQUESTED';
ALTER TABLE "Incident" ADD COLUMN "sourceSyncError" TEXT;
ALTER TABLE "Incident" ADD COLUMN "sourceSyncedAt" DATETIME;
ALTER TABLE "Incident" ADD COLUMN "sourceSyncLockedUntil" REAL NOT NULL DEFAULT 0;
ALTER TABLE "ChatConversation" ADD COLUMN "incidentId" TEXT;
DROP INDEX IF EXISTS "Incident_tenantId_source_externalId_key";
DROP INDEX IF EXISTS "Incident_organizationId_source_externalId_key";
CREATE UNIQUE INDEX "Incident_tenantId_integrationId_source_externalId_key" ON "Incident"("tenantId", "integrationId", "source", "externalId");
ALTER TABLE "RootCauseAnalysis" ADD COLUMN "recommendedSteps" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "Incident" ADD COLUMN "investigationDispatchedAt" DATETIME;
ALTER TABLE "Incident" ADD COLUMN "remediationDispatchedAt" DATETIME;
UPDATE "Incident" SET "investigationDispatchedAt" = "updatedAt", "remediationDispatchedAt" = "updatedAt";
CREATE INDEX "Integration_syncEnabled_id_idx" ON "Integration"("syncEnabled", "id");
CREATE INDEX "Incident_status_updatedAt_idx" ON "Incident"("status", "updatedAt");
